# Generated by Django 5.0.3 on 2024-03-14 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_task_frequency_days"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="completed_last",
            new_name="completed_last_date",
        ),
    ]
